### ISSUE TITLE
[Feature Request] Translations for "Mod Settings"

### ISSUE THREAD

**Issue by FeBe95** [jackhumbert/mod_settings#25]
It would be awesome to have the "Mod Settings" menu item translated, so it would fit in with all the other localized menu items.

E.g. for German it would be:
```
Mod-Einstellungen
```

**Comment by jackhumbert** [comment]
I added the ability for this in https://github.com/jackhumbert/mod_settings/commit/73c585f9c9e37453c9c58916150b718fb78c9c40 (will be in the v0.2.14 release) - you should be able to create an archive with `base\localization\*-*\onscreens\mod_settings.json` and load it with the appropriate .xl file, like the one below (for `en-us`):

```yaml
localization:
  onscreens:
    en-us: base\localization\en-us\onscreens\mod_settings.json
```
